# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-02 14:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbpro', '0003_user_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='desc',
        ),
    ]
